### ISSUE TITLE
[FEATURE REQUEST] AWTRIX should maybe use a different font

### ISSUE THREAD

**Issue by RobertoCravallo** [Blueforcer/awtrix-light#438] opened 2023-12-22 08:15 UTC
# Different fonts for AWTRIX

### Is your feature request related to a problem?

NO!

### Describe the solution / feature you'd like

Upload own fonts (seems to not be possible as per a previous request!!)

### Describe alternatives you've considered

Use AWTRIX as is!

### Additional context

Basically, this thing just rocks!!! Thank you, by the way!!! The "problem" is with lower case letters like the "w", which are hardly recognizable. Maybe you can generally use a "cleaner" font.

On the AWTRIX 2 this was possible and I saw a video with a really nice "w". ;-)

Grüße aus Mannheim....

![IdAW – Home Assistant 2023-12-22 08-58-58](https://github.com/Blueforcer/awtrix-light/assets/112649622/cd97ebdf-292c-4c4f-ac9f-1070cc32c7f7)

**Comment by Blueforcer** [comment] 2023-12-22 09:40
Duplicate of https://github.com/Blueforcer/awtrix-light/issues/53


Awtrix 2 uses the same font, and it also wasn't possible to change the font.

**Comment by RobertoCravallo** [comment] 2023-12-22 10:26
Ups, misunderstood something there!!! Maybe it was a bigger display? Thanx.

**Closed** 2023-12-23 17:18 UTC
Labels: feature request
