### ISSUE TITLE
[BUG] Clock keep restarting few times a day

### ISSUE THREAD

**Issue by zkrystian** [Blueforcer/awtrix-light#86] opened 2023-04-24 18:34 UTC
# Bug report

## Describe the bug

Ulanzi clock keep restarting few times a day. Beginning of the logs is just before restart. 
Some logs have weird signs like "setCurrentApp: Publish current app P�?"

## Additional information

- Devices involved:
  - Model: Ulanzi Awtrix Smart Pixel Clock 2882 (TC001)
  - AWTRIX-LIGHT version: 0.57

## Logs

```
setCurrentApp: Publish current app pm10
setCurrentApp: Publish current app space
E (586) esp_core_dump_flash: No core du��partition found!
E (587) esp_core_dump_flash: No core dump partition found!
[  2093][E][vfssetup: Setup periphery
loadSettings: Webserver configuration loaded
setMatrixLayout: Set matrix layout to 0
Framebuffer_GFX::begin Width: 32 Height: 8 Num Pixels: 256
Connecting to boost
..........................setup: My IP: 192.168.0.24
setup: Webserver loaded
Homeassistant discovery disabled
connect: Connecting to MQTT with login
checkUpdate: Check firmwareversion
checkUpdate: 
Device already on latest firmware version: 0.57

onMqttConnected: MQTT Connected
onMqttConnected: Subscribe to topic /brightness
onMqttConnected: Subscribe to topic /notify/dismiss
onMqttConnected: Subscribe to topic /notify
onMqttConnected: Subscribe to topic /timer
onMqttConnected: Subscribe to topic /custom/#
onMqttConnected: Subscribe to topic /switch
onMqttConnected: Subscribe to topic /settings
onMqttConnected: Subscribe to topic /previousapp
onMqttConnected: Subscribe to topic /nextapp
onMqttConnected: Subscribe to topic /doupdate
onMqttConnected: Subscribe to topic /nextapp
onMqttConnected: Subscribe to topic /apps
onMqttConnected: Subscribe to topic /power
onMqttConnected: Subscribe to topic /indicator1
onMqttConnected: Subscribe to topic /indicator2
onMqttConnected: Subscribe to topic /timeformat
onMqttConnected: Subscribe to topic /dateformat
onMqttConnected: Subscribe to topic /reboot
onMqttMessage: MQTT message received at topic awtrix_2fbd58/custom/planesoverhead
onMqttMessage: Payload:  {"text":1,"icon":"31805","lifetime":300}
[ 20896][E][vfs_api.cpp:105] open(): /littlefs/ICONS/31805.jpg does not exist, no permits for creation
onMqttMessage: MQTT message received at topic awtrix_2fbd58/custom/planes
onMqttMessage: Payload:  {"text":3,"icon":"31805","lifetime":300}
[ 21058][E][vfs_api.cpp:105] open(): /littlefs/ICONS/31805.jpg does not exist, no permits for creation
setCurrentApp: Publish current app Date
setCurrentApp: Publish current app $'�?
setCurrentApp: Publish current app planes
setCurrentApp: Publish current app temp_outside
setCurrentApp: Publish current app P�?
setCurrentApp: Publish current app pressure
setCurrentApp: Publish current app windspeed
```

**Comment by Blueforcer** [comment] 2023-04-24 19:44
duplicate of https://github.com/Blueforcer/awtrix-light/issues/84

**Closed by Blueforcer** 2023-04-24 19:44 UTC
Labels: bug
